# ------------------------------------------------------
# GUNSMITH Configuration File (config.yml)
# 
# Editing the settings in this file will change the way
# GunSmith works on your server. To reset this file to
# its default values, simply delete your config.yml and
# stop/restart your server.
# ------------------------------------------------------
#
# LOADED MARKER | Dummy value to check against at start-up, don't change!
loaded: true
# 
# LANGUAGE | Currently supported languages: English, Spanish
language: English
# 
# GLASS BREAK | If true, fired firearm rounds will break glass on contact.
glassBreak: false
#
# SILENT MODE | If true, most messages will not be relayed to players.
silentMode: false
#
# GUI ENABLED | If true, players can freely access GS items from a menu.
guiEnabled: true
#
# OP REQUIREMENT | If true, players must have OP permissions to use the GS GUI.
opRequirement: false
# 
# EXPLOSIONS ENABLED | If true, players can use firearms like the RPG to destroy blocks.
explosions: false
# 
# PERMISSIONS REQUIREMENT | If true, players must have the proper permissions to use GunSmith.
permissions: false
#
# CRAFTING ENABLED | If true, players can craft firearms and related custom recipes at the workbench.
crafting: false
#
# CRAFTING ENABLED | If true, fired rounds will emit a smokey particle trail.
particles: true
#
# FOR MORE INFO | https://www.spigotmc.org/threads/gunsmith.189617/